"use client";

import { useEffect, useState, useRef, useCallback } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import {
  ArrowLeftIcon,
  CheckCircleIcon,
  ArrowPathIcon,
  SparklesIcon,
  PhotoIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import { apiFetch } from "@/lib/api-client";
import { useAuthStore } from "@/stores/auth-store";
import { toast } from "sonner";
import { getSignedUploadUrl } from "./actions";

// ─── Types ───────────────────────────────────────────────────────────────────

interface ArticleImage {
  id: string;
  url: string;
  alt_text: string | null;
  sort_order: number;
}

interface ComposerState {
  // Identity
  articleId: string | null;
  tempArticleId: string | null;

  // Form fields
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  status: "draft" | "published" | "archived";
  featuredImageUrl: string;
  images: ArticleImage[];

  // UX state
  isDirty: boolean;
  isSaving: boolean;
  lastSavedAt: Date | null;
  saveError: string | null;
  isLoading: boolean;

  // Autosave
  autosaveTimer: ReturnType<typeof setTimeout> | null;
}

// ─── Helper Functions ─────────────────────────────────────────────────────────

function generateSlug(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
}

async function uploadCoverImageToR2(
  file: File,
  articleId: string,
): Promise<string> {
  try {
    // Generate object key
    const timestamp = Date.now();
    const sanitized = file.name
      .toLowerCase()
      .replace(/[^a-z0-9.-]/g, "-")
      .replace(/-+/g, "-");
    const objectKey = `articles/${articleId}/cover-${timestamp}-${sanitized}`;

    // Get signed URL from server action
    const {
      objectKey: key,
      uploadUrl,
      publicUrl,
    } = await getSignedUploadUrl(
      objectKey,
      file.type as any,
      300, // 5 minutes expiry
    );

    // Upload to R2
    await new Promise<void>((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open("PUT", uploadUrl);
      xhr.setRequestHeader("Content-Type", file.type);
      xhr.onload = () =>
        xhr.status === 200 ? resolve() : reject(new Error(xhr.statusText));
      xhr.onerror = () => reject(new Error("Upload failed"));
      xhr.send(file);
    });

    return publicUrl;
  } catch (error) {
    console.error("Error uploading cover image:", error);
    throw new Error("Gagal mengunggah gambar cover");
  }
}

// ─── Article Composer Page ──────────────────────────────────────────────────

export default function ArticleComposerPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const editId = searchParams.get("id");
  const isAuthenticated = useAuthStore((s) => s.isAuthenticated);
  const clearUser = useAuthStore((s) => s.clearUser);

  // State
  const [articleId, setArticleId] = useState<string | null>(editId ?? null);
  const [tempArticleId, setTempArticleId] = useState<string | null>(null);
  const [title, setTitle] = useState("");
  const [slug, setSlug] = useState("");
  const [excerpt, setExcerpt] = useState("");
  const [content, setContent] = useState("");
  const [status, setStatus] = useState<"draft" | "published" | "archived">(
    "draft",
  );
  const [coverImageFile, setCoverImageFile] = useState<File | null>(null);
  const [coverImagePreview, setCoverImagePreview] = useState<string>("");
  const [featuredImageUrl, setFeaturedImageUrl] = useState("");
  const [images, setImages] = useState<ArticleImage[]>([]);
  const [isDirty, setIsDirty] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isUploadingCover, setIsUploadingCover] = useState(false);
  const [lastSavedAt, setLastSavedAt] = useState<Date | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(!!editId);
  const autosaveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const coverImageInputRef = useRef<HTMLInputElement>(null);
  const slugAutoGeneratedRef = useRef(true);

  // ─── Auth Check ───────────────────────────────────────────────────────────

  useEffect(() => {
    if (!isAuthenticated) {
      router.replace(
        `/auth/login?redirect=/admin/articles/compose${editId ? `?id=${editId}` : ""}`,
      );
    }
  }, [isAuthenticated, router, editId]);

  // ─── Load Existing Article (Edit Mode) ─────────────────────────────────────

  const loadArticle = useCallback(
    async (id: string) => {
      setIsLoading(true);
      try {
        const res = await apiFetch(`/api/cms/articles/${id}`);
        if (!res.ok) {
          if (res.status === 401) {
            clearUser();
            router.replace("/auth/login?redirect=/admin/articles/compose");
          } else {
            router.push("/admin/articles");
          }
          return;
        }
        const { article } = await res.json();

        setArticleId(article.id);
        setTitle(article.title ?? "");
        setSlug(article.slug ?? "");
        setExcerpt(article.excerpt ?? "");
        setContent(article.content ?? "");
        setStatus(article.status ?? "draft");
        setFeaturedImageUrl(article.featured_image_url ?? "");
        setImages(article.article_images ?? []);
        setIsDirty(false);
        setLastSavedAt(new Date());
      } catch {
        router.push("/admin/articles");
      } finally {
        setIsLoading(false);
      }
    },
    [router, clearUser],
  );

  useEffect(() => {
    if (editId) {
      loadArticle(editId);
    }
  }, [editId, loadArticle]);

  // ─── Auto-Slug from Title ──────────────────────────────────────────────────

  useEffect(() => {
    if (title && slugAutoGeneratedRef.current) {
      const auto = generateSlug(title);
      setSlug(auto);
    }
  }, [title]);

  // ─── Mark Dirty & Autosave Timer ──────────────────────────────────────────

  const markDirty = useCallback(() => {
    setIsDirty(true);
    setLastSavedAt(null);

    if (autosaveTimerRef.current) {
      clearTimeout(autosaveTimerRef.current);
    }

    autosaveTimerRef.current = setTimeout(() => {
      // Will be triggered by performAutosave via dependency
    }, 30_000);
  }, []);

  // ─── Save Functions ────────────────────────────────────────────────────────

  const saveArticle = useCallback(
    async (
      options: {
        autosave?: boolean;
        newStatus?: "draft" | "published" | "archived";
      } = {},
    ) => {
      if (!title.trim()) {
        setSaveError("Judul artikel wajib diisi");
        return false;
      }

      setIsSaving(true);
      setSaveError(null);

      try {
        // Step 1: Ensure article exists
        let currentArticleId = articleId;

        if (!currentArticleId) {
          const createRes = await apiFetch("/api/cms/articles/draft", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ temp_title: title.trim() }),
          });

          if (!createRes.ok) {
            const err = await createRes.json();
            setSaveError(err.error || "Gagal membuat artikel");
            return false;
          }

          const { article_id } = await createRes.json();
          currentArticleId = article_id;
          setArticleId(article_id);
          setTempArticleId(article_id);
        }

        // Step 2: Upload cover image if selected (parallel with article save)
        let uploadedCoverUrl = featuredImageUrl;
        let uploadError: string | null = null;

        if (coverImageFile && currentArticleId) {
          setIsUploadingCover(true);
          try {
            uploadedCoverUrl = await uploadCoverImageToR2(
              coverImageFile,
              currentArticleId,
            );
            setCoverImageFile(null);
            setCoverImagePreview("");
          } catch (err) {
            uploadError =
              err instanceof Error
                ? err.message
                : "Gagal mengunggah gambar cover";
          } finally {
            setIsUploadingCover(false);
          }

          if (uploadError) {
            setSaveError(uploadError);
            return false;
          }
        }

        // Step 3: Update article metadata
        const updatePayload: Record<string, unknown> = {
          title: title.trim(),
          slug: slug || undefined,
          excerpt: excerpt.trim() || undefined,
          content: content.trim() || undefined,
          featured_image_url: uploadedCoverUrl || undefined,
          autosave: options.autosave ?? false,
        };

        if (options.newStatus) {
          updatePayload.status = options.newStatus;
        }

        const updateRes = await apiFetch(
          `/api/cms/articles/${currentArticleId}`,
          {
            method: "PATCH",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(updatePayload),
          },
        );

        if (!updateRes.ok) {
          const err = await updateRes.json();
          setSaveError(err.error || "Gagal menyimpan artikel");
          return false;
        }

        const { article } = await updateRes.json();

        // Update local state with server response
        setStatus(article.status);
        setFeaturedImageUrl(uploadedCoverUrl);

        if (!options.autosave) {
          setIsDirty(false);
          setLastSavedAt(new Date());
          if (options.newStatus === "published") {
            toast.success("Artikel dipublikasi");
          } else {
            toast.success("Draf disimpan");
          }
        }

        return true;
      } catch {
        setSaveError("Terjadi kesalahan. Silakan coba lagi.");
        return false;
      } finally {
        setIsSaving(false);
      }
    },
    [
      title,
      slug,
      excerpt,
      content,
      coverImageFile,
      featuredImageUrl,
      articleId,
    ],
  );

  const performAutosave = useCallback(async () => {
    if (!articleId || isSaving) return;
    await saveArticle({ autosave: true });
  }, [articleId, isSaving, saveArticle]);

  // Update autosave timer with the actual performAutosave function
  useEffect(() => {
    autosaveTimerRef.current = setTimeout(() => {
      if (isDirty && articleId && !isSaving) {
        performAutosave();
      }
    }, 30_000);

    return () => {
      if (autosaveTimerRef.current) {
        clearTimeout(autosaveTimerRef.current);
      }
    };
  }, [isDirty, articleId, isSaving, performAutosave]);

  const handleSaveDraft = () => {
    saveArticle({ newStatus: "draft", autosave: false });
  };

  const handlePublish = () => {
    saveArticle({ newStatus: "published", autosave: false });
  };

  // ─── Cover Image Handlers ──────────────────────────────────────────────────

  const handleCoverImageSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate file size (max 10MB)
    if (file.size > 10 * 1024 * 1024) {
      setSaveError("Ukuran gambar terlalu besar (maksimal 10MB)");
      return;
    }

    // Create preview
    const reader = new FileReader();
    reader.onload = (event) => {
      const preview = event.target?.result as string;
      setCoverImageFile(file);
      setCoverImagePreview(preview);
      markDirty();
    };
    reader.readAsDataURL(file);

    // Reset input
    if (coverImageInputRef.current) {
      coverImageInputRef.current.value = "";
    }
  };

  const handleRemoveCoverImage = () => {
    setCoverImageFile(null);
    setCoverImagePreview("");
    if (featuredImageUrl) {
      // If there was a previously uploaded image, keep it
      setFeaturedImageUrl(featuredImageUrl);
    }
    markDirty();
  };

  // ─── Before Unload Guard ──────────────────────────────────────────────────

  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (!isDirty) return;

      // If article was never published (draft only), flag for cleanup
      if (tempArticleId && status === "draft") {
        localStorage.setItem("draft_cleanup_id", tempArticleId);
      }

      e.preventDefault();
      e.returnValue = "Anda memiliki perubahan yang belum disimpan.";
    };

    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => window.removeEventListener("beforeunload", handleBeforeUnload);
  }, [isDirty, tempArticleId, status]);

  // ─── Render ───────────────────────────────────────────────────────────────

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-gray-50">
        <div className="text-center">
          <ArrowPathIcon className="h-12 w-12 text-gray-400 mx-auto mb-4 animate-spin" />
          <p className="text-gray-500">Memuat artikel...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="sticky top-0 z-40 bg-white border-b border-gray-200 shadow-sm">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between gap-4">
            {/* Back Button + Title */}
            <div className="flex items-center gap-4 flex-1 min-w-0">
              <button
                onClick={() => router.push("/admin/articles")}
                className="flex-shrink-0 p-2 text-gray-400 hover:text-gray-600 rounded-lg hover:bg-gray-100 transition-colors"
                title="Kembali"
              >
                <ArrowLeftIcon className="h-5 w-5" />
              </button>
              <div className="flex-1 min-w-0">
                <input
                  type="text"
                  value={title}
                  onChange={(e) => {
                    setTitle(e.target.value);
                    markDirty();
                    slugAutoGeneratedRef.current = false;
                  }}
                  placeholder="Judul Artikel"
                  className="w-full text-lg font-bold text-gray-900 placeholder-gray-400 border-0 bg-transparent focus:outline-none focus:ring-0"
                />
              </div>
            </div>

            {/* Save Status */}
            <div className="flex items-center gap-3 flex-shrink-0">
              {isSaving && (
                <div className="flex items-center gap-1.5 text-sm text-gray-500">
                  <ArrowPathIcon className="h-4 w-4 animate-spin" />
                  <span>Menyimpan...</span>
                </div>
              )}
              {isDirty && !isSaving && !lastSavedAt && (
                <span className="text-sm text-amber-600">● Belum disimpan</span>
              )}
              {!isSaving && lastSavedAt && (
                <div className="flex items-center gap-1.5 text-sm text-gray-400">
                  <CheckCircleIcon className="h-4 w-4 text-green-500" />
                  <span>
                    Tersimpan{" "}
                    {Math.floor((Date.now() - lastSavedAt.getTime()) / 1000) <
                    60
                      ? `${Math.floor((Date.now() - lastSavedAt.getTime()) / 1000)}d`
                      : `${Math.floor((Date.now() - lastSavedAt.getTime()) / 60000)}m`}{" "}
                    lalu
                  </span>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Error Message */}
        {saveError && (
          <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
            <p className="text-sm text-red-600">{saveError}</p>
          </div>
        )}

        {/* Slug Field - Auto-generated from Judul */}
        <div className="mb-6">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Slug (URL) - Otomatis dari Judul
          </label>
          <div className="flex items-center gap-2">
            <span className="text-sm text-gray-500">
              wargadigital.id/artikel/
            </span>
            <input
              type="text"
              value={slug}
              onChange={(e) => {
                setSlug(e.target.value);
                slugAutoGeneratedRef.current = false;
                markDirty();
              }}
              onFocus={() => {
                slugAutoGeneratedRef.current = false;
              }}
              placeholder="slug-otomatis-dari-judul"
              className="flex-1 px-3 py-2 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            {slugAutoGeneratedRef.current && (
              <div className="flex items-center gap-1.5 text-xs text-gray-400">
                <SparklesIcon className="h-3.5 w-3.5" />
                <span>Auto</span>
              </div>
            )}
          </div>
        </div>

        {/* Excerpt */}
        <div className="mb-6">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Ringkasan (Opsional)
          </label>
          <textarea
            value={excerpt}
            onChange={(e) => {
              setExcerpt(e.target.value);
              markDirty();
            }}
            placeholder="Ringkasan singkat artikel..."
            rows={2}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        {/* Content */}
        <div className="mb-6">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Konten
          </label>
          <textarea
            value={content}
            onChange={(e) => {
              setContent(e.target.value);
              markDirty();
            }}
            placeholder="Tulis artikel Anda di sini..."
            rows={12}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm"
          />
        </div>

        {/* Gambar Cover Upload */}
        <div className="mb-6">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Gambar Cover
          </label>
          <input
            ref={coverImageInputRef}
            type="file"
            accept="image/jpeg,image/png,image/webp,image/gif"
            onChange={handleCoverImageSelect}
            className="hidden"
          />
          {!coverImagePreview && !featuredImageUrl ? (
            <button
              type="button"
              onClick={() => coverImageInputRef.current?.click()}
              className="w-full flex flex-col items-center justify-center gap-2 px-4 py-8 border-2 border-dashed border-gray-300 rounded-lg hover:border-blue-400 hover:bg-blue-50 transition-colors"
            >
              <PhotoIcon className="h-8 w-8 text-gray-400" />
              <span className="text-sm text-gray-600">
                Klik untuk memilih gambar cover
              </span>
              <span className="text-xs text-gray-400">
                JPEG, PNG, WebP, atau GIF (Max 10MB)
              </span>
            </button>
          ) : (
            <div className="relative rounded-lg overflow-hidden border border-gray-200">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={coverImagePreview || featuredImageUrl}
                alt="Cover"
                className="w-full h-48 object-cover"
              />
              <div className="absolute top-2 right-2 flex gap-2">
                <button
                  type="button"
                  onClick={() => coverImageInputRef.current?.click()}
                  className="px-3 py-1 bg-white/90 text-gray-700 text-xs font-medium rounded hover:bg-white transition-colors"
                >
                  Ganti
                </button>
                <button
                  type="button"
                  onClick={handleRemoveCoverImage}
                  className="p-1 bg-red-500 text-white rounded hover:bg-red-600 transition-colors"
                >
                  <XMarkIcon className="h-4 w-4" />
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Status Selector */}
        <div className="mb-8">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Status
          </label>
          <select
            value={status}
            onChange={(e) => {
              setStatus(e.target.value as "draft" | "published" | "archived");
              markDirty();
            }}
            className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="draft">Draf</option>
            <option value="published">Dipublikasi</option>
            <option value="archived">Diarsipkan</option>
          </select>
        </div>

        {/* Info Box for New Articles */}
        {!articleId && (
          <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg mb-8">
            <p className="text-xs text-blue-700">
              💡 Simpan artikel terlebih dahulu, lalu Anda bisa menambahkan
              gambar galeri pada mode edit.
            </p>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="sticky bottom-0 z-40 bg-white border-t border-gray-200 shadow-lg">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-2 text-sm">
              {(isSaving || isUploadingCover) && (
                <>
                  <ArrowPathIcon className="h-4 w-4 animate-spin text-blue-600" />
                  <span className="text-gray-600">
                    {isUploadingCover ? "Mengunggah gambar..." : "Menyimpan..."}
                  </span>
                </>
              )}
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => router.push("/admin/articles")}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
              >
                Batal
              </button>
              <button
                onClick={handleSaveDraft}
                disabled={isSaving || isUploadingCover || !title.trim()}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 border border-gray-300 rounded-lg hover:bg-gray-200 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Simpan Draf
              </button>
              <button
                onClick={handlePublish}
                disabled={isSaving || isUploadingCover || !title.trim()}
                className="px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Publikasi
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
